[env]
_.path = ["~/.cargo/bin"]
XRAY_CGO = "1"
GOOS = "linux"
GOARCH = "amd64"

[tools]
go = "1.26"
zig = "0.15"
rust = { version = "stable", targets = "x86_64-unknown-linux-musl,aarch64-unknown-linux-musl", components = "rust-src" }
task = "latest"
